version: 2.1
jobs:
  print-hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "hello"
  print-world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "world"
  print-var:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run: 
          name: "echo an env var that is part of our project"
          command: |
            echo $MY_NAME # this env var must be set within the project
workflows:
  welcome:
    jobs:
      - print-hello
      - print-world:
          requires:
            - print-hello
      - print-var:
          requires:
            - print-world
